@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant Master #lightblue
participant PhysicianService #lightblue
participant PatientService #lightblue
participant Database #lightblue

Master -> PhysicianService : HTTP Read Physician
PhysicianService -> Database : JDBC Read Physician
Database --> PhysicianService : Response
PhysicianService --> Master : Response

Master -> PatientService: HTTP Read Patient
PatientService -> Database : JDBC Read Patient
Database -> Database : Error
Database --> PatientService : Exception

PatientService --> Master : Exception

@enduml